import React, { useState } from 'react';

const Trans = ({ inputText }) => {
    const [translatedText, setTranslatedText] = useState("");
    const [imagePrompt, setImagePrompt] = useState("");
    const [imageUrl, setImageUrl] = useState("");

    const handleTranslate = async () => {
        try {
            const response = await fetch('http://localhost:5000/translation', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    text: inputText,
                    source: 'ko',  // 필요 시 변경
                    target: 'en'   // 필요 시 변경
                }),
            });

            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(errorData.error || '번역에 실패했습니다.');
            }

            const data = await response.json();
            setTranslatedText(data.translated_text);
            setImagePrompt(data.image_prompt);
            setImageUrl(data.image_url);  // 이미지 URL 설정
        } catch (error) {
            setTranslatedText(`Error: ${error.message}`);
            console.error('Translation Error:', error);
        }
    };

    return (
        <div>
            <button onClick={handleTranslate}>번역 및 이미지 생성</button>
            <div>
                <h3>번역 결과:</h3>
                <p>{translatedText}</p>
                <h3>이미지 생성 프롬프트:</h3>
                <p>{imagePrompt}</p>
                {imageUrl && (
                    <div>
                        <h3>생성된 이미지:</h3>
                        <img src={imageUrl} alt="Generated by DALL-E" style={{ maxWidth: '100%' }} />
                    </div>
                )}
            </div>
        </div>
    );
};

export default Trans;
